[2024-04-21T14:34:18.454+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: accident_api_pipeline.install_pip_packages manual__2024-04-21T14:01:30.768499+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
